export const QUERY_LOADING = 'QUERY_LOADING'
export const FETCH_QUERY_SUCCESS = 'FETCH_QUERY_SUCCESS'
export const FETCH_QUERY_FAILURE = 'FETCH_QUERY_FAILURE'

export const BIN_LOADING = 'BIN_LOADING'
export const FETCH_BIN_SUCCESS = 'FETCH_BIN_SUCCESS'
export const FETCH_BIN_FAILURE = 'FETCH_BIN_FAILURE'

export const APPROVED_ITEMS_LOADING = 'APPROVED_ITEMS_LOADING'
export const FETCH_APPROVED_ITEMS_SUCCESS = 'FETCH_APPROVED_ITEMS_SUCCESS'
export const FETCH_APPROVED_ITEMS_FAILURE = 'FETCH_APPROVED_ITEMS_FAILURE'

export const TICKETS_LOADING = 'TICKETS_LOADING'
export const FETCH_TICKETS_SUCCESS = 'FETCH_TICKETS_SUCCESS'
export const FETCH_TICKETS_FAILURE = 'FETCH_TICKETS_FAILURE'

export const ADD_ITEM_STARTED = 'ADD_ITEM_STARTED'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'

export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAILURE = 'REMOVE_ITEM_SUCCESS'

export const EDIT_ITEM_STARTED = 'EDIT_ITEM_STARTED'
export const EDIT_ITEM_SUCCESS = 'EDIT_ITEM_SUCCESS'
export const EDIT_ITEM_FAILURE = 'EDIT_ITEM_FAILURE'

export const APPROVE_TICKET_STARTED = 'APPROVE_TICKET_STARTED'
export const APPROVE_TICKET_SUCCESS = 'APPROVE_TICKET_SUCCESS'
export const APPROVE_TICKET_FAILURE = 'APPROVE_TICKET_FAILURE'

export const RESET_ITEMS = 'RESET_ITEMS'


//USERS

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
